//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PM
    {
        public int ID { get; set; }
        public Nullable<int> IDPM { get; set; }
        public string IDDG { get; set; }
        public string TenDG { get; set; }
        public Nullable<int> IDSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual TrangThai TrangThai1 { get; set; }
    }
}
